pypy/pypy.org

Makefile
conf.py
pages/search.html
themes/pypy/templates/localsearch.tmpl

This works locally, so it downloads the text of the whole site and searches it. Currently that is 1.6MB, which does not seem too extreme yet.

Add a search field in the navbar via the localsearch plugin

---

conf.py

as requested in a comment to #8

extend rss feed to full posts

---

conf.py
posts/2021/03/new-hpy-blog.md

Also, set `FUTURE_IS_NOW=True`, else new posts don't show up in the preview

Advertise the new HPy blog

---

themes/pypy/templates/index.tmpl
themes/pypy/templates/post.tmpl
themes/pypy/templates/post_header.tmpl
themes/pypy/templates/static_comments_helper.tmpl

should fix the "No comment - Comments" in post headers

tweak formatting when there are no static comments

---

css/site.css
themes/pypy/assets/css/styles.css

xref hpyproject/hpyproject.org#15, doint it here instead since there are more pages to preview the change

remove unused css and also 'visited' styling

---

conf.py
pages/contact.rst
posts/2021/05/pypy-irc-moves-to-libera-chat.md

Parallel HPy PR: https://github.com/hpyproject/hpyproject.org/pull/18

officially migrate from freenode to libera.chat

---

pages/compat.rst

remove stdlib from the website compat overview

---

posts/2021/12/error-message-style-guides.txt

checked for conciseness and clarity

---

posts/2022/02/nlp-icelandic-pypy.rst

draft blog post by Vilhjálmur Þorsteinsson (@vthorsteinsson)

blog post 'Natural Language Processing for Icelandic with PyPy: A Case Study'

---

posts/2022/03/how-is-pypy-tested.rst
posts/2022/04/how-is-pypy-tested.rst

just a draft, not ready for merging yet, but I want to generate a preview

a blog post draft on testing PyPy

---

posts/2022/07/m1-support-for-pypy.txt

A short blog post about the M1 work

add a M1 blog post

---

conf.py
pages/contact.rst
pages/howtohelp.rst
pages/pypy-sponsors.md

add a sponsors page, link to it instead of 'People'

---

conf.py
pages/download_advanced.rst

Fix macos download links, add section on macos arm64
thanks @reagle

fix macos download links

---

pages/checksums.rst
pages/download.rst
pages/download_advanced.rst
posts/2022/12/pypy-v7311-release.txt

release v7.3.11. According to https://www.pypy.org/categories/release.html, I think I have created about 40 releases since 2.4 in 2014.

add checksums, release note for v7.3.11

---

pages/download_advanced.rst

Due to [issue 3880](https://foss.heptapod.net/pypy/pypy/-/issues/3880)

document dropping macos 10.14

---

posts/2023/06/pypy-v7312-release.txt
posts/2023/09/pypy-v7313-release.txt

typo in blog title

---

pages/contact.rst
pages/download_advanced.rst
pages/people.rst
pages/performance.rst
posts/2023/12/pypy-moved-to-git-github.md
themes/pypy/assets/css/styles.css

blog post about the move to github

add post about the move to github

---

posts/2023/12/pypy-moved-to-git-github.md

see https://github.com/pypy/pypy/issues/4979

add an update to the github announcement post about the off-by-one errors in issue numbers

---

.github/workflows/nikola.yml
README.md
pages/download_advanced.rst
pages/people.rst
pages/pypy-sponsors.md
posts/2021/04/some-uses-of-graphviz.txt
posts/2021/05/pypy-v735-release.rst
posts/2021/10/pypy-v737-release.rst
posts/2022/12/pypy-v7311-release.txt
posts/2023/12/pypy-moved-to-git-github.md
posts/2023/12/pypy-v7314-release.txt
posts/2024/03/fixing-bug-incremental-gc.md
posts/2024/05/vmprof-firefox.md
posts/2024/07/mining-jit-traces-missing-optimizations-z3.md
posts/2024/07/toy-abstract-interpretation.md
posts/2024/08/toy-knownbits.md

* #132 plus automate the testing in GitHub Actions

Add codespell to GitHub Actions

---

.github/workflows/nikola.yml
.pre-commit-config.yaml
Makefile
plugins/static_comments/static_comments.py
pyproject.toml

* #135 but remove the standard pre-commit hooks to focus only on codespell.

Add pre-commit only for codespell

---

posts/2023/01/string-concatenation-is-quadratic.rst
posts/2023/05/rpython-used-to-speed-up-risc-v-simulation-over-15x.txt
posts/2024/03/fixing-bug-incremental-gc.md

trying to get gh-pages to rebuild...

abbreviate my name
